/* Nomes em português dos aparelhos — SÓ os que o brasileiro usa traduzido.
   O que se usa em inglês no Brasil (Leg Press 45, Hack, Smith, Crossover,
   Hip Thrust, Air Bike, Power Cage, Reformer…) fica como está.
   Chave: nome original normalizado (minúsculas, sem pontuação). */
window.TORQUE_NOMES_PT = {
  /* ---- pernas ---- */
  '45 degree leg press': 'Leg Press 45',
  '70 degree leg press': 'Leg Press 70',
  '90 degree leg press': 'Leg Press 90',
  'horizontal leg press': 'Leg Press Horizontal',
  'seated leg press': 'Leg Press Sentado',
  'seated leg press machine': 'Leg Press Sentado',
  'leg press machine': 'Leg Press',
  'linear leg press': 'Leg Press Linear',
  'super vertlcal leg press': 'Leg Press Vertical',
  'leg press hack squat': 'Leg Press + Hack',
  'combo leg press hack squat': 'Leg Press + Hack Conjugado',
  'leg extension': 'Cadeira Extensora',
  'seated leg extension': 'Cadeira Extensora',
  'seated leg extension unit': 'Cadeira Extensora',
  'iso lateral leg extension': 'Cadeira Extensora Iso-Lateral',
  'leg curl': 'Flexora',
  'seated leg curl': 'Cadeira Flexora',
  'prone leg curl': 'Mesa Flexora',
  'horizontal leg curl': 'Mesa Flexora',
  'kneeling leg curl': 'Flexora Ajoelhada',
  'kneeling leg bend': 'Flexora Ajoelhada',
  'kneeling leg flexion': 'Flexora Ajoelhada',
  'leg curl extension': 'Extensora / Flexora Conjugada',
  'leg cuarl extension': 'Extensora / Flexora Conjugada',
  'seated leg extension curl combo': 'Extensora / Flexora Conjugada',
  'hack squat': 'Agachamento Hack',
  'huck squat': 'Agachamento Hack',
  'hack squat shoulder lift': 'Hack + Desenvolvimento',
  'hack squat shoulder lif': 'Hack + Desenvolvimento',
  'pendulum trainer': 'Agachamento Pêndulo',
  'super pendulum squat': 'Agachamento Pêndulo',
  'adductor': 'Cadeira Adutora',
  'inner thigh': 'Cadeira Adutora',
  'thigh inner trainer': 'Cadeira Adutora',
  'outer thigh': 'Cadeira Abdutora',
  'thigh outer trainer': 'Cadeira Abdutora',
  'hip abduction': 'Cadeira Abdutora',
  'standing abductor': 'Abdutora em Pé',
  'standing hip abduction': 'Abdutora em Pé',
  'hip abduction adduction': 'Adutora / Abdutora Conjugada',
  'inner outer': 'Adutora / Abdutora Conjugada',
  'inner outer thigh': 'Adutora / Abdutora Conjugada',
  'seated calf': 'Panturrilha Sentado',
  'seated calf trainer': 'Panturrilha Sentado',
  'standing calf raise': 'Panturrilha em Pé',
  'calf heel lift': 'Panturrilha em Pé',
  'calf extension': 'Panturrilha (Extensão)',
  'calf trainer': 'Panturrilha',
  'calf tibialis trainer': 'Panturrilha + Tibial',
  'tibia dorsi flexion': 'Tibial Anterior',
  'glute exercise': 'Máquina de Glúteos',
  'rear kick': 'Glúteo (Coice)',
  'hip bridge': 'Elevação Pélvica',
  '3d hip bridge': 'Elevação Pélvica 3D',
  'bridge hip trainer': 'Elevação Pélvica',
  'hip thruster': 'Hip Thrust',
  'hip thrust glute': 'Hip Thrust',
  'standing hip thrust': 'Hip Thrust em Pé',
  'deadlift shrug': 'Terra / Encolhimento',
  'squat rack': 'Rack de Agachamento',
  'wall squat rack': 'Rack de Agachamento de Parede',
  /* ---- peito ---- */
  'chest press': 'Supino Máquina',
  'seated chest press': 'Supino Máquina',
  'adjustable chest press': 'Supino Máquina Regulável',
  'incline chest press': 'Supino Inclinado Máquina',
  'inclined chest press': 'Supino Inclinado Máquina',
  'incline press': 'Supino Inclinado Máquina',
  'flat chest press trainer': 'Supino Reto Máquina',
  'flat chest press traine': 'Supino Reto Máquina',
  'wide chest press': 'Supino Aberto Máquina',
  'iso lateral wide chest press': 'Supino Aberto Iso-Lateral',
  'iso lateral bench wide chest': 'Supino Aberto Iso-Lateral',
  'iso lateral bench press': 'Supino Iso-Lateral',
  'iso lateral horizontal press': 'Supino Horizontal Iso-Lateral',
  'iso lateral chest back': 'Supino / Remada Iso-Lateral',
  'horizontal press': 'Supino Horizontal Máquina',
  'pec fly': 'Crucifixo Máquina (Peck Deck)',
  'pectoral fly': 'Crucifixo Máquina (Peck Deck)',
  'seated chest fly': 'Crucifixo Máquina',
  'incline chest fly': 'Crucifixo Inclinado Máquina',
  'pearl delt pec fly': 'Crucifixo / Posterior de Ombro',
  'adjustable crossover': 'Crossover Ajustável',
  /* ---- costas ---- */
  'lat pulldown': 'Puxada Alta (Pulley)',
  'lat pull down': 'Puxada Alta (Pulley)',
  'pull down': 'Puxada Alta (Pulley)',
  'lat pulldown back': 'Puxada Alta (Pulley)',
  'lat pulldown row': 'Puxada Alta / Remada',
  'lat puldown low row': 'Puxada Alta / Remada Baixa',
  'lat pulldown triceps dip': 'Puxada Alta / Paralela',
  'iso lateral wide pulldown': 'Puxada Aberta Iso-Lateral',
  'high pull': 'Puxada Alta',
  'high low pull': 'Puxada Alta e Baixa',
  'low pull': 'Remada Baixa',
  'low row': 'Remada Baixa',
  'iso lateral low row': 'Remada Baixa Iso-Lateral',
  'seated row': 'Remada Sentada',
  'sitting row': 'Remada Sentada',
  'back extension': 'Extensão Lombar',
  'hyper extension': 'Hiperextensão Lombar',
  'reverse hyperextension': 'Hiperextensão Reversa',
  'roman chair': 'Cadeira Romana',
  'back abdominal combo': 'Lombar / Abdominal Conjugado',
  'shrug machine': 'Encolhimento (Trapézio)',
  /* ---- ombros ---- */
  'shoulder press': 'Desenvolvimento de Ombros',
  'seated shoulder press': 'Desenvolvimento Sentado',
  'lateral shoulder press': 'Desenvolvimento Lateral',
  'sitting shoulder lift': 'Desenvolvimento Sentado',
  'shoulder lift': 'Desenvolvimento de Ombros',
  'lateral raise': 'Elevação Lateral',
  'seated standing lateral raise': 'Elevação Lateral (Sentado/Em Pé)',
  'side lift trainer': 'Elevação Lateral',
  'lateral deltoids': 'Deltoide Lateral',
  'delt machine': 'Máquina de Deltoides',
  'military bench': 'Banco Militar',
  'shoulder bench': 'Banco para Desenvolvimento',
  /* ---- braços ---- */
  'bicep curl': 'Rosca Bíceps',
  'biceps curl': 'Rosca Bíceps',
  'bicep trainer': 'Máquina de Bíceps',
  'preacher curl': 'Rosca Scott',
  'seated preacher curl': 'Rosca Scott Sentado',
  'bicep bench': 'Banco Scott',
  'biceps curl triceps': 'Bíceps / Tríceps Conjugado',
  'biceps triceps extension': 'Bíceps / Tríceps Conjugado',
  'biceps triceps exercises': 'Bíceps / Tríceps Conjugado',
  'super french press': 'Tríceps Francês',
  'tricep pushdown': 'Tríceps Pulley',
  'triceps press down': 'Tríceps Pulley',
  'triceps press': 'Tríceps Máquina',
  'triceps dip': 'Paralela (Tríceps)',
  'seated dip': 'Mergulho Sentado (Dip)',
  'assistance dip chin': 'Graviton (Barra/Paralela Assistida)',
  'dip chin assist': 'Graviton (Barra/Paralela Assistida)',
  'pull up assistance exercise': 'Graviton (Barra Assistida)',
  'standing pull up assistance exercise': 'Graviton em Pé (Barra Assistida)',
  'pull up and dip station': 'Estação Barra Fixa / Paralela',
  /* ---- abdômen e core ---- */
  'abdominal crunch': 'Abdominal Máquina',
  'abdoina crunch': 'Abdominal Máquina',
  'abdominal machine': 'Abdominal Máquina',
  'abdominal oblique crunch': 'Abdominal Oblíquo Máquina',
  'reverse crunches': 'Abdominal Invertido',
  'abdominal bench': 'Banco de Abdominal',
  'adjustable crunch bench': 'Banco de Abdominal Regulável',
  'rotary torso': 'Rotação de Tronco',
  'torso rotation trainer': 'Rotação de Tronco',
  /* ---- bancos e suportes ---- */
  'flat bench': 'Banco Reto',
  'adjustable flat bench': 'Banco Reto Regulável',
  'adjustable bench': 'Banco Regulável',
  'decline bench': 'Banco Declinado',
  'adjustable decline bench': 'Banco Declinado Regulável',
  'utility bench': 'Banco Multiuso',
  'multi purpose bench': 'Banco Multiuso',
  'multi functional bench': 'Banco Multifuncional',
  'dumbbell bench': 'Banco para Halteres',
  'multifunctional dumbbell bench': 'Banco Multifuncional para Halteres',
  'olympic bench': 'Banco Olímpico',
  'olympic bench flat': 'Banco Olímpico Reto',
  'olympic bench incline': 'Banco Olímpico Inclinado',
  'olympic incline bench': 'Banco Olímpico Inclinado',
  'olympic decline bench': 'Banco Olímpico Declinado',
  'olympic seated bench': 'Banco Olímpico Sentado',
  'bench press rack': 'Rack de Supino',
  'multifunctional bench press rack': 'Rack de Supino Multifuncional',
  'dumbbell rack': 'Suporte de Halteres',
  'dumbbell rack 15 pairs': 'Suporte de Halteres (15 pares)',
  'double dumbbell rack': 'Suporte Duplo de Halteres',
  'barbell rack': 'Suporte de Barras',
  'kettlebell rack': 'Suporte de Kettlebells',
  'plate tree': 'Suporte de Anilhas',
  /* ---- cardio ---- */
  'commercial treadmill': 'Esteira Profissional',
  'commercial treadmill led': 'Esteira Profissional LED',
  'commercial treadmill mirror': 'Esteira Profissional (Espelho)',
  'commercial treadmill 21 5inch mirror': 'Esteira Profissional (Espelho 21,5")',
  'home treadmill': 'Esteira Residencial',
  'curved treadmill': 'Esteira Curva',
  'pet curved treadmill': 'Esteira Curva Pet',
  'elliptical machine': 'Elíptico',
  'high end horizontal elliptical machine': 'Elíptico Horizontal Premium',
  'upright bike': 'Bicicleta Ergométrica Vertical',
  'recumbent bike': 'Bicicleta Ergométrica Horizontal',
  'spining bike': 'Bike de Spinning',
  'magnetic spinning bike': 'Bike de Spinning Magnética',
  'stair climber': 'Simulador de Escada',
  'ski machine': 'Simulador de Esqui',
  'surfing machine': 'Simulador de Surf',
  'kayak ergometer': 'Simulador de Caiaque',
  'water rowing machine': 'Remo Ergométrico (Água)',
  'air rowing machine': 'Remo Ergométrico (Ar)',
  'stretching': 'Alongamento'
};
