const test = require('node:test');
const assert = require('node:assert/strict');
const M = require('../custos/model.js');
const zeros = () => Object.fromEntries(M.FIELDS.map(([key])=>[key,key==='cambio'?5:0]));
const product = {codigo:'TEST-ONLY',preco:2000};
test('FOB and all cost categories, without markup',()=>{const d=zeros();d.portoBRL=100;d.comissaoPct=10;const r=M.calculate(product,d,{fobUSD:100});assert.equal(r.base,500);assert.equal(r.total,800);assert.equal(r.difference,1200);assert.equal(r.margin,60);assert.equal(r.markup,150);assert.equal(r.breakEven,666.67);});
test('unknown expenses are not zero',()=>{const d=zeros();delete d.portoBRL;const r=M.calculate(product,d,{fobUSD:100});assert.equal(r.base,500);assert.equal(r.total,null);assert.equal(r.difference,null);assert.ok(r.missing.includes('portoBRL'));});
test('zero is explicit and accepted',()=>{assert.equal(M.calculate(product,zeros(),{fobUSD:100}).complete,true);});
test('an explicit zero overrides a global expense',()=>{const d=zeros();d.portoBRL=400;assert.equal(M.calculate(product,d,{fobUSD:100,portoBRL:0}).total,500);});
test('actual landed cost bypasses only the legacy base',()=>{const d=zeros();delete d.cambio;d.entregaBRL=120;const r=M.calculate(product,d,{landedBRL:900});assert.equal(r.total,1020);assert.equal(r.method,'documentado');});
test('credits subtract, never count as markup',()=>{const d=zeros();d.creditosBRL=100;assert.equal(M.calculate(product,d,{fobUSD:100}).total,400);});
test('excessive credits are invalid',()=>{const d=zeros();d.creditosBRL=1000;assert.ok(M.calculate(product,d,{fobUSD:100}).error);});
test('sales rates >= 100% are invalid',()=>{const d=zeros();d.comissaoPct=60;d.pagamentoPct=40;assert.ok(M.calculate(product,d,{fobUSD:100}).error);});
test('ICMS 100% cannot produce Infinity',()=>{const d=zeros();d.icms=100;const r=M.calculate(product,d,{fobUSD:100});assert.equal(r.total,null);assert.ok(r.error);});
test('published zero price is not invented',()=>{const r=M.calculate({preco:0},zeros(),{fobUSD:100});assert.equal(r.margin,null);assert.equal(r.total,null);assert.equal(r.breakEven,500);});
test('negative margin is displayed, not clamped',()=>{const r=M.calculate({preco:100},zeros(),{fobUSD:100});assert.equal(r.difference,-400);assert.equal(r.margin,-400);});
test('null overrides inherit defaults',()=>{assert.equal(M.calculate(product,zeros(),{fobUSD:100,portoBRL:null}).total,500);});
test('legacy formula exactly matches the existing model',()=>{const d=zeros();Object.assign(d,{cambio:5.3,freteIntlUSD:42,seguroPct:1,iof:.38,ii:14,ipi:5,pisCofins:11.75,icms:18,freteNacionalBRL:150});const r=M.calculate(product,d,{fobUSD:700});const legacy=(700+42+700*.01)*(1+(.38+14+5+11.75)/100)/(1-.18)*5.3+150;assert.equal(r.base,M.round(legacy));});
test('Brazilian decimals',()=>{assert.equal(M.parse('1.234,56'),1234.56);assert.equal(M.parse('5,3'),5.3);assert.equal(M.parse('5.3'),5.3);assert.equal(M.parse(''),null);});
test('invalid and nonfinite input rejected',()=>{for(const x of ['20abc','Infinity','-3','1,2,3','1.234.5',Infinity])assert.throws(()=>M.parse(x));});
test('profit and discount are not allowed cost inputs',()=>{assert.throws(()=>M.validate({margem:200}));assert.throws(()=>M.validate({descontoPct:10}));});
test('negative, zero FX and excessive amounts rejected',()=>{assert.throws(()=>M.validate({cambio:0}));assert.throws(()=>M.validate({portoBRL:-1}));assert.throws(()=>M.validate({fobUSD:1e12}));});
test('legacy import ignores margin, discount, unknown products and duplicates',()=>{const x=M.legacyImport({params:{cambio:5,margem:200,descontoPct:20},items:[{codigo:'TEST-ONLY',fob:100},{codigo:'TEST-ONLY',fob:200},{codigo:'UNKNOWN',fob:100}]},[product]);assert.equal(x.defaults.cambio,5);assert.equal(x.defaults.margem,undefined);assert.equal(x.defaults.descontoPct,undefined);assert.equal(x.items.length,1);assert.equal(x.items[0].payload.fobUSD,100);});
test('no fallback from selling price to cost',()=>{assert.equal(M.calculate(product,zeros(),{}).base,null);});
test('spreadsheet formula injection is neutralized',()=>{for(const s of ['=CMD()','+SUM(A1)','-CMD()','@SUM(A1)','  =1+1'])assert.ok(M.csvCell(s).startsWith('"\''));assert.equal(M.csvCell('A"9'),'"A""9"');});
test('independent models do not mutate catalogue or inputs',()=>{const d=zeros();const p={...product};const i={fobUSD:100};const before=JSON.stringify([d,p,i]);M.calculate(p,d,i);assert.equal(JSON.stringify([d,p,i]),before);});
